### ISSUE TITLE
git push and npm install fail today

### ISSUE THREAD

**Issue by plancien** [nodester/nodester#148]
Hi,
(I'm Toxicode_fr on Twitter, thanks for providing me the link to here)

I had a working app a few days ago, but today I tried a git push nodester, and I got :

```
The authenticity of host 'nodester.com (50.16.203.53)' can't be established.
(...)
Permission denied (publickey).
```

I tried to send again my public key, and now I have : 

```
exec request failed on channel 0
fatal: The remote end hung up unexpectedly
```

I tried deleting my app and recreating a new one, but it didn't sole the issue.
And when I try a

```
nodester npm install myapp express
```

I have :

```
/usr/local/lib/node_modules/nodester-cli/lib/npm.js:40
                            if (l[1].toLowerCase() === 'warn') {
                                 ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at /usr/local/lib/node_modules/nodester-cli/lib/npm.js:40:38
    at Array.forEach (native)
    at /usr/local/lib/node_modules/nodester-cli/lib/npm.js:34:21
    at [object Object].callback (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/nodester.js:44:5)
    at [object Object].<anonymous> (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:273:21)
    at [object Object].emit (events.js:64:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:261:54)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:132:23)
    at Socket.ondata (http.js:1212:22)
```

**Comment by DanBUK** [comment]
I have fixed a few things today, please re-test.

**Comment by plancien** [comment]
nope, but something changed : 

```
git push nodester
fatal: '/node/hosted_apps/plancien/2602-0776f7b8035c97aa018c5e4e6bede83b.git' does not appear to be a git repository
fatal: The remote end hung up unexpectedly
```

I checked nodester app info, to see if the repo changed, but it's the same I used

**Comment by DanBUK** [comment]
That looked to not be there, i've recreated the repo, please re-push to it.

**Comment by plancien** [comment]
Yes, the push is now working again, thanks !

The second error is still there :

nodester npm install express@2.3.12
nodester info installing to app: nodegame
nodester info installing these npm packages: express@2.3.12
nodester ├── mime@1.2.2
nodester ├── qs@0.2.0
nodester └── connect@1.5.2

```
/usr/local/lib/node_modules/nodester-cli/lib/npm.js:40
                        if (l[1].toLowerCase() === 'warn') {
                                 ^
TypeError: Cannot call method 'toLowerCase' of undefined
at /usr/local/lib/node_modules/nodester-cli/lib/npm.js:40:38
at Array.forEach (native)
at /usr/local/lib/node_modules/nodester-cli/lib/npm.js:34:21
at [object Object].callback (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/nodester.js:44:5)
at [object Object].<anonymous> (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:273:21)
at [object Object].emit (events.js:64:17)
at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:261:54)
at IncomingMessage.emit (events.js:81:20)
at HTTPParser.onMessageComplete (http.js:132:23)
at Socket.ondata (http.js:1212:22)
```

**Comment by DanBUK** [comment]
I know that issue, I'll take a look shortly.

**Comment by DanBUK** [comment]
I just pushed nodester-cli v@0.2.14 to fix this error, please npm install nodester-cli and re-test please.

**Comment by plancien** [comment]
yes it's working ! Well done, and thanks !
