### ISSUE TITLE
Connection refused, errno: 111, CLI shows app running fine

### ISSUE THREAD

**Issue by akiva** [nodester/nodester#157]
My app pushes and runs all commands just fine via CLI, yet when I try to connect to the URL, I get this error

> An error has occurred: {"stack":"Error: ECONNREFUSED, Connection refused\n    at Socket._onConnect (net.js:601:18)
> at IOWatcher.onWritable [as callback](net.js:186:12)","message":"ECONNREFUSED, Connection
> refused","errno":111,"code":"ECONNREFUSED","syscall":"connect"}

Logs show:

> Error: EADDRINUSE, Address already in use
>    at HTTPServer._doListen (net.js:1100:5)
>    at net.js:1071:14
>    at Object.lookup (dns.js:153:45)
>    at HTTPServer.listen (net.js:1065:20)
>    at Object.<anonymous> (/app/app.js:40:5)
>    at Module._compile (module.js:402:26)
>    at Object..js (module.js:408:10)
>    at Module.load (module.js:334:31)
>    at Function._load (module.js:293:12)
>    at Array.<anonymous> (module.js:421:10)
> 
> Process died with exit code 1. Restarting...
> Warning: connection.session() MemoryStore is not
> designed for a production environment, as it will leak
> memory, and obviously only work within a single process.
> 
> node.js:134
> 
> ```
>    throw e; // process.nextTick error, or 'error' event on first tick
> ```

Any help or pointers much appreciated.

**Comment by akiva** [comment]
Another hosted app I know about, as well as the link to the Nodester IRC room both have the same or similar errors. Perhaps this is not just me.

**Comment by akiva** [comment]
When I try to update the Express module via nodester app install ... I get this error:

/usr/local/lib/node_modules/nodester-cli/lib/npm.js:85
                            l[1] = l[1].white;
                                       ^
TypeError: Cannot read property 'white' of undefined
    at /usr/local/lib/node_modules/nodester-cli/lib/npm.js:85:40
    at Array.forEach (native)
    at /usr/local/lib/node_modules/nodester-cli/lib/npm.js:79:21
    at [object Object].callback (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/nodester.js:44:5)
    at [object Object].<anonymous> (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:273:21)
    at [object Object].emit (events.js:64:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:261:54)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1226:22)

**Comment by jryan388** [comment]
I'm having the same problem. I can't access the logs; I get a 500 error.

**Comment by DanBUK** [comment]
akiva - For the nodester npm install error, update you nodester-cli. That bug was fixed last week.

As to your app not running, what are you putting in your .listen() call. The recommened approach is to use listen(process.env['app_port']) to ensure that you listen on the correct port allocated to your application. From the output above I can see that it think the address/port combination is in use; that is why the app isn't starting.

**Comment by DanBUK** [comment]
Also akiva, what is the git path to the application that is failing?

**Comment by DanBUK** [comment]
Akiva, you have the following line in app.js: app.listen(3000); Which I am assuming you were using for development. If you check nodester app artofthemenu info you will see that it's supposed to listen on port 10963.

**Comment by akiva** [comment]
Hello Dan,

Thanks for the reply. I did update on Friday to no avail, the issue remained. I changed the ports as you mentioned and all worked as planned. Somehow I missed this pivotal piece of information in your documents/tutorial. 

FYI. Your IRC chat room seems to still be down with the same error my site was returning.

**Comment by DanBUK** [comment]
FYI you can always just use IRC, irc.nodester.com channel #nodester
