### ISSUE TITLE
Cannot ssh to git@nodester

### ISSUE THREAD

**Issue by lostinplace** [nodester/nodester#241]
I have run nodester user setkey (several times, most recently with the default id_rsa)
When I attempt to ssh to git@nodester.com I receive the response "Connection closed by 50.16.203.53

This occurs after my id_rsa is offered in negotiation

**Comment by yocontra** [comment]
Message me your key and I'll make sure everything is being added properly

**Comment by lostinplace** [comment]
sent!

**Comment by jgoodall** [comment]
I am getting the same error:

$ git push nodester master -v
Pushing to git@nodester.com:/node/git/ ... .git
Connection closed by 50.16.203.53
fatal: The remote end hung up unexpectedly

**Comment by quantumpotato** [comment]
Hi @Contra I e-mailed you my public key & info, I'm also having this issue.
Has anyone got this working?

**Comment by AG-cmwheeler** [comment]
Not working as of 11:16 EST 8 December 2011

**Comment by yocontra** [comment]
Working on it now, sorry for the inconvenience. Will update with details

**Comment by quantumpotato** [comment]
Thanks for the quick reply!
Looking forward to it.

On Fri, Dec 9, 2011 at 12:24 AM, Contra <
reply@reply.github.com

**Comment by yocontra** [comment]
Still having issues figuring out what exactly the problem is... everything appears to be fine and this only seems to be affecting users who used our last batch of coupons. I'll update again when I have more info

**Comment by abendigo** [comment]
I am having the same problem. I got my coupon ages ago, but only got around to using it last night.

**Comment by yocontra** [comment]
Fixed in 0d9b8bd1b4b579fdb408809d258317f6cd7becef. Somebody had an invalid ssh key that was messing everything up. A filter has been applied on all new keys and the existing ones were sanitized. I recommend everyone `nodester user setkey` if you have any issues connecting still. After that, `nodester app init <your app name>` and you should be good to go. Sorry this took so long to fix! Let me know if you have any issues

**Comment by quantumpotato** [comment]
Working! Thanks @Contra

**Comment by lostinplace** [comment]
Confirmed this is working.  Thanks

**Comment by newtriks** [comment]
Working for me also thanks!

**Comment by susansarabia** [comment]
Not working for me... i setkey and init my app and still not working... help

**Comment by Scribblerockerz** [comment]
I reset my ssh key and create a new app, but it still doesn't work... need help too...

**Comment by isra** [comment]
Scribblerockerz you found solution?

**Comment by Scribblerockerz** [comment]
Not really, I decided to change the hosting service to http://cloudno.de
They have a nice Getting started guide.
So it works for me now, but the problem with nodester still alive...

**Comment by yocontra** [comment]
@Scribblerockerz - BTW cloudno.de is running the same version as nodester

**Comment by Scribblerockerz** [comment]
I said "Not really", It means I have no idea why it works now...
The "setkey" was my problem... maybe It works because I registered with a new ssh key.
I don't know,..

**Comment by nutic** [comment]
After deleting and recreating app I have:

nodester info Attemping to start app:
nodester ERROR Fatal Error! API Response: undefined
Reason: No response received.

I have two apps on nodester and the second is ok.

**Comment by zishon89us** [comment]
i just tried to push my existing node app to nodester at "git push nodester master"
i get this error
"fatal: 'nodester' does not appear to be a git repository"
"fatal: The remote end hung up unexpectedly"

**Comment by zishon89us** [comment]
plz help anyone if u can
